## Optimizing Retail Prices with Machine Learning Techniques

### Aim
The objective of this project is to implement a machine learning framework 
for retail price optimization, focusing on determining the optimal selling price 
of products or services to maximize revenue and profit margins.

In this project, you will learn how to leverage various machine learning techniques 
in Python to analyze historical sales data, understand market dynamics, and 
derive pricing strategies that enhance profitability. The methodology will cover 
data preprocessing, feature engineering, model selection, and evaluation metrics 
pertinent to pricing models.


### Overview
This article serves as a comprehensive guide for those interested in applying 
machine learning methodologies to retail price optimization. It will provide a 
step-by-step walkthrough of the entire process, from data preparation to the 
implementation of machine learning algorithms, culminating in actionable insights 
for retail pricing strategies.

### What is Retail Price Optimization?
Retail price optimization refers to the process of determining the optimal price 
for products or services to achieve the best balance between revenue and sales volume. 
The goal is to establish a pricing strategy that maximizes profitability while attracting 
a sufficient number of customers to purchase the products.

This involves leveraging data analytics and various pricing strategies to identify the most 
effective price points. Effective retail price optimization takes into account multiple factors 
that can influence product pricing, including:

- Cost of Goods Sold (COGS): The direct costs associated with producing or acquiring a product.
- Market Demand: The willingness of customers to purchase a product at various price levels.
- Competitive Pricing: The prices charged by competitors for similar products.
- Customer Segmentation: Understanding different customer groups and their respective price sensitivities.
- Seasonality: Changes in demand based on seasonal trends or events.
- Promotional Strategies: Discounts, sales, and other marketing tactics that can affect pricing.
- Economic Conditions: Factors such as inflation, unemployment rates, and overall economic climate.

For the task of retail price optimization, you will require a dataset that includes 
historical prices of products or services, along with other relevant variables that influence pricing.

I have identified an ideal dataset for this task, which you can download from 
Kaggle: https://www.kaggle.com/datasets/suddharshan/retail-price-optimization.

import kagglehub

### Download latest version
path = kagglehub.dataset_download("suddharshan/retail-price-optimization")

print("Path to dataset files:", path)

### Dataset Overview for Retail Price Optimization
This dataset contains transaction data for retail products, which can be used 
to analyze and optimize pricing strategies. It includes information on product 
sales, pricing, shipping costs, customer ratings, and various time-related 
factors such as month, year, and holidays. The insights derived from this data 
can help identify optimal pricing for maximizing revenue and profitability.

In [2]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
pio.templates.default = "plotly_white"

data = pd.read_csv(r"D:\Vinu UK\Resume Projecst\ML\retail_price.csv")
data

,product_id,product_category_name,month_year,qty,total_price,freight_price,unit_price,product_name_lenght,product_description_lenght,product_photos_qty,...,comp_1,ps1,fp1,comp_2,ps2,fp2,comp_3,ps3,fp3,lag_price
0,bed1,bed_bath_table,01-05-2017,1,45.95,15.100000,45.950000,39,161,2,...,89.9,3.9,15.011897,215.000000,4.4,8.760000,45.95,4.0,15.100000,45.900000
1,bed1,bed_bath_table,01-06-2017,3,137.85,12.933333,45.950000,39,161,2,...,89.9,3.9,14.769216,209.000000,4.4,21.322000,45.95,4.0,12.933333,45.950000
2,bed1,bed_bath_table,01-07-2017,6,275.70,14.840000,45.950000,39,161,2,...,89.9,3.9,13.993833,205.000000,4.4,22.195932,45.95,4.0,14.840000,45.950000
3,bed1,bed_bath_table,01-08-2017,4,183.80,14.287500,45.950000,39,161,2,...,89.9,3.9,14.656757,199.509804,4.4,19.412885,45.95,4.0,14.287500,45.950000
4,bed1,bed_bath_table,01-09-2017,2,91.90,15.100000,45.950000,39,161,2,...,89.9,3.9,18.776522,163.398710,4.4,24.324687,45.95,4.0,15.100000,45.950000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,bed5,bed_bath_table,01-05-2017,1,215.00,8.760000,215.000000,56,162,5,...,89.9,3.9,15.011897,215.000000,4.4,8.760000,45.95,4.0,15.100000,214.950000
672,bed5,bed_bath_table,01-06-2017,10,2090.00,21.322000,209.000000,56,162,5,...,89.9,3.9,14.769216,209.000000,4.4,21.322000,45.95,4.0,12.933333,215.000000
673,bed5,bed_bath_table,01-07-2017,59,12095.00,22.195932,205.000000,56,162,5,...,89.9,3.9,13.993833,205.000000,4.4,22.195932,45.95,4.0,14.840000,209.000000
674,bed5,bed_bath_table,01-08-2017,52,10375.00,19.412885,199.509804,56,162,5,...,89.9,3.9,14.656757,199.509804,4.4,19.412885,45.95,4.0,14.287500,205.000000
675,bed5,bed_bath_table,01-09-2017,32,5222.36,24.324687,163.398710,56,162,5,...,89.9,3.9,18.776522,163.398710,4.4,24.324687,45.95,4.0,15.100000,199.509804

In [3]:
print(data.head()) # Display first few rows of the dataset

print(data.info()) # Display basic information about the dataset

print(data.describe()) # Display summary statistics

  product_id product_category_name  month_year  qty  total_price  \
0       bed1        bed_bath_table  01-05-2017    1        45.95
1       bed1        bed_bath_table  01-06-2017    3       137.85
2       bed1        bed_bath_table  01-07-2017    6       275.70
3       bed1        bed_bath_table  01-08-2017    4       183.80
4       bed1        bed_bath_table  01-09-2017    2        91.90

   freight_price  unit_price  product_name_lenght  product_description_lenght  \
0      15.100000       45.95                   39                         161
1      12.933333       45.95                   39                         161
2      14.840000       45.95                   39                         161
3      14.287500       45.95                   39                         161
4      15.100000       45.95                   39                         161

   product_photos_qty  ...  comp_1  ps1        fp1      comp_2  ps2  \
0                   2  ...    89.9  3.9  15.011897  215.000000  4.4
1                   2  ...    89.9  3.9  14.769216  209.000000  4.4
2                   2  ...    89.9  3.9  13.993833  205.000000  4.4
3                   2  ...    89.9  3.9  14.656757  199.509804  4.4
4                   2  ...    89.9  3.9  18.776522  163.398710  4.4

         fp2  comp_3  ps3        fp3  lag_price
0   8.760000   45.95  4.0  15.100000      45.90
1  21.322000   45.95  4.0  12.933333      45.95
2  22.195932   45.95  4.0  14.840000      45.95
3  19.412885   45.95  4.0  14.287500      45.95
4  24.324687   45.95  4.0  15.100000      45.95

[5 rows x 30 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 676 entries, 0 to 675
Data columns (total 30 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  676 non-null    object
 1   product_category_name       676 non-null    object
 2   month_year                  676 non-null    object
 3   qty                         676 non-null    int64
 4   total_price                 676 non-null    float64
 5   freight_price               676 non-null    float64
 6   unit_price                  676 non-null    float64
 7   product_name_lenght         676 non-null    int64
 8   product_description_lenght  676 non-null    int64
 9   product_photos_qty          676 non-null    int64
 10  product_weight_g            676 non-null    int64
 11  product_score               676 non-null    float64
 12  customers                   676 non-null    int64
 13  weekday                     676 non-null    int64
 14  weekend                     676 non-null    int64
 15  holiday                     676 non-null    int64
 16  month                       676 non-null    int64
 17  year                        676 non-null    int64
 18  s                           676 non-null    float64
 19  volume                      676 non-null    int64
 20  comp_1                      676 non-null    float64
 21  ps1                         676 non-null    float64
 22  fp1                         676 non-null    float64
 23  comp_2                      676 non-null    float64
 24  ps2                         676 non-null    float64
 25  fp2                         676 non-null    float64
 26  comp_3                      676 non-null    float64
 27  ps3                         676 non-null    float64
 28  fp3                         676 non-null    float64
 29  lag_price                   676 non-null    float64
dtypes: float64(15), int64(12), object(3)
memory usage: 158.6+ KB
None
              qty   total_price  freight_price  unit_price  \
count  676.000000    676.000000     676.000000  676.000000
mean    14.495562   1422.708728      20.682270  106.496800
std     15.443421   1700.123100      10.081817   76.182972
min      1.000000     19.900000       0.000000   19.900000
25%      4.000000    333.700000      14.761912   53.900000
50%     10.000000    807.890000      17.518472   89.900000
75%     18.000000   1887.322500      22.713558  129.990000
max    122.000000  12095.000000      79.760000  364.000000

       product_name_lenght  product_description_lenght  product_photos_qty  \
count           676.000000                  676.000000          676.000000
mean             48.720414                  767.399408            1.994083
std               9.420715                  655.205015            1.420473
min              29.000000                  100.000000            1.000000
25%              40.000000                  339.000000            1.000000
50%              51.000000                  501.000000            1.500000
75%              57.000000                  903.000000            2.000000
max              60.000000                 3006.000000            8.000000

       product_weight_g  product_score   customers  ...      comp_1  \
count        676.000000     676.000000  676.000000  ...  676.000000
mean        1847.498521       4.085503   81.028107  ...   79.452054
std         2274.808483       0.232021   62.055560  ...   47.933358
min          100.000000       3.300000    1.000000  ...   19.900000
25%          348.000000       3.900000   34.000000  ...   49.910000
50%          950.000000       4.100000   62.000000  ...   69.900000
75%         1850.000000       4.200000  116.000000  ...  104.256549
max         9750.000000       4.500000  339.000000  ...  349.900000

              ps1         fp1      comp_2         ps2         fp2      comp_3  \
count  676.000000  676.000000  676.000000  676.000000  676.000000  676.000000
mean     4.159467   18.597610   92.930079    4.123521   18.620644   84.182642
std      0.121652    9.406537   49.481269    0.207189    6.424174   47.745789
min      3.700000    0.095439   19.900000    3.300000    4.410000   19.900000
25%      4.100000   13.826429   53.900000    4.100000   14.485000   53.785714
50%      4.200000   16.618984   89.990000    4.200000   16.811765   59.900000
75%      4.200000   19.732500  117.888889    4.200000   21.665238   99.990000
max      4.500000   57.230000  349.900000    4.400000   57.230000  255.610000

              ps3         fp3   lag_price
count  676.000000  676.000000  676.000000
mean     4.002071   17.965007  107.399684
std      0.233292    5.533256   76.974657
min      3.500000    7.670000   19.850000
25%      3.900000   15.042727   55.668750
50%      4.000000   16.517110   89.900000
75%      4.100000   19.447778  129.990000
max      4.400000   57.230000  364.000000

[8 rows x 27 columns]

In [4]:
missing_values = data.isnull().sum()
print("Missing values in each column:\n", missing_values)

missing_percentage = (missing_values / len(data)) * 100
print("Percentage of missing values:\n", missing_percentage)

Missing values in each column:
 product_id                    0
product_category_name         0
month_year                    0
qty                           0
total_price                   0
freight_price                 0
unit_price                    0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_score                 0
customers                     0
weekday                       0
weekend                       0
holiday                       0
month                         0
year                          0
s                             0
volume                        0
comp_1                        0
ps1                           0
fp1                           0
comp_2                        0
ps2                           0
fp2                           0
comp_3                        0
ps3                           0
fp3                           0
lag_price                     0
dtype: int64
Percentage of missing values:
 product_id                    0.0
product_category_name         0.0
month_year                    0.0
qty                           0.0
total_price                   0.0
freight_price                 0.0
unit_price                    0.0
product_name_lenght           0.0
product_description_lenght    0.0
product_photos_qty            0.0
product_weight_g              0.0
product_score                 0.0
customers                     0.0
weekday                       0.0
weekend                       0.0
holiday                       0.0
month                         0.0
year                          0.0
s                             0.0
volume                        0.0
comp_1                        0.0
ps1                           0.0
fp1                           0.0
comp_2                        0.0
ps2                           0.0
fp2                           0.0
comp_3                        0.0
ps3                           0.0
fp3                           0.0
lag_price                     0.0
dtype: float64

In [27]:
print("Unique product categories:", data['product_category_name'].unique())
print("Unique customers:", data['customers'].unique())

category_counts = data['product_category_name'].value_counts()
print("Counts of product categories:\n", category_counts)

Unique product categories: ['bed_bath_table' 'garden_tools' 'consoles_games' 'health_beauty'
 'cool_stuff' 'perfumery' 'computers_accessories' 'watches_gifts'
 'furniture_decor']
Unique customers: [ 57  61 123  90  54  50  97  41  62  43  34  26  15  21  17  74 113 115
 146 339 184 137 160 116 111  13  33  38  49  30   6   3   2   1 102  58
  46  19  25  23  53  82  89  81 139 112  98 126 169 159 131 127  42  39
  20  45  18 118   4   7   8  27  12  10  31  35 152 202 107  66  78  29
  48  91  73  59 125 178 260  93 122  16  14  22  11  36   9  64  40  52
  83  92  95   5]
Counts of product categories:
 product_category_name
garden_tools             160
health_beauty            130
watches_gifts            103
computers_accessories     69
bed_bath_table            61
cool_stuff                57
furniture_decor           48
perfumery                 26
consoles_games            22
Name: count, dtype: int64

In [6]:
total_sales = data.groupby('product_category_name')['total_price'].sum().reset_index()
print("Total Sales by Product Category:\n", total_sales)

average_unit_price = data.groupby('product_category_name')['unit_price'].mean().reset_index()
print("Average Unit Price by Category:\n", average_unit_price)

Total Sales by Product Category:
    product_category_name  total_price
0         bed_bath_table     95084.52
1  computers_accessories    142097.95
2         consoles_games      5800.70
3             cool_stuff     57956.30
4        furniture_decor     56925.16
5           garden_tools    163582.54
6          health_beauty    212409.24
7              perfumery     20312.52
8          watches_gifts    207582.17
Average Unit Price by Category:
    product_category_name  unit_price
0         bed_bath_table   78.629278
1  computers_accessories  119.482323
2         consoles_games   27.033766
3             cool_stuff  107.857512
4        furniture_decor   60.154262
5           garden_tools   80.094699
6          health_beauty  132.309870
7              perfumery   89.348813
8          watches_gifts  164.880007

In [16]:
import pandas as pd
import plotly.express as px

# Load the dataset
data = pd.read_csv('retail_price.csv')

# Create a histogram for total_price
fig = px.histogram(data, 
                   x='total_price', 
                   nbins=20, 
                   title='Distribution of Total Price')

# Show the figure in the default browser
fig.show(renderer='browser')

In [18]:
fig = px.box(data, 
             y='unit_price', 
             title='Box Plot of Unit Price')
fig.show(renderer='browser')

In [23]:
import statsmodels.api as sm
fig = px.scatter(data, 
                 x='qty', 
                 y='total_price', 
                 title='Quantity vs Total Price', trendline="ols")
fig.show(renderer='browser')

In [24]:
fig = px.bar(data, x='product_category_name', 
             y='total_price', 
             title='Average Total Price by Product Category')
fig.show(renderer = "browser")

In [25]:
fig = px.box(data, x='weekday', 
             y='total_price', 
             title='Box Plot of Total Price by Weekday')
fig.show(renderer = "browser")

In [29]:
# Select only numeric columns
numeric_data = data.select_dtypes(include=['number'])

# Calculate the correlation matrix
correlation_matrix = numeric_data.corr()

# Create the heatmap
import plotly.graph_objects as go

fig = go.Figure(go.Heatmap(
    x=correlation_matrix.columns, 
    y=correlation_matrix.columns, 
    z=correlation_matrix.values
))
fig.update_layout(title='Correlation Heatmap of Numerical Features')
fig.show(renderer = "browser")

In [32]:
data['comp_price_diff'] = data['unit_price'] - data['comp_1'] 

avg_price_diff_by_category = data.groupby('product_category_name')['comp_price_diff'].mean().reset_index()

fig = px.bar(avg_price_diff_by_category, 
             x='product_category_name', 
             y='comp_price_diff', 
             title='Average Competitor Price Difference by Product Category')
fig.update_layout(
    xaxis_title='Product Category',
    yaxis_title='Average Competitor Price Difference'
)
fig.show(renderer = "browser")

## Retail Price Optimization Model with Machine Learning

In [38]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Prepare your data
X = data[['qty', 'unit_price', 'comp_1', 'product_score', 'comp_price_diff']]
y = data['total_price']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize models
models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest": RandomForestRegressor(),
    "Gradient Boosting": GradientBoostingRegressor(),
    "Support Vector Regressor": SVR()
}

# Store results
results = {}

# Train and evaluate each model
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    mse = mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    
    results[name] = {'MSE': mse, 'MAE': mae, 'R²': r2}

# Create a DataFrame to display results
results_df = pd.DataFrame(results).T
print(results_df)

# Visualize Predicted vs Actual for each model
fig = go.Figure()

for name, model in models.items():
    y_pred = model.predict(X_test)
    fig.add_trace(go.Scatter(x=y_test, y=y_pred, mode='markers', name=name))

# Ideal prediction line
fig.add_trace(go.Scatter(x=[min(y_test), max(y_test)], y=[min(y_test), max(y_test)],
                         mode='lines', marker=dict(color='red'), name='Ideal Prediction'))

fig.update_layout(
    title='Predicted vs. Actual Retail Price',
    xaxis_title='Actual Retail Price',
    yaxis_title='Predicted Retail Price'
)

fig.show(renderer="browser")

                                   MSE          MAE        R²
Linear Regression         5.392636e+05   430.432487  0.829289
Decision Tree             1.430029e+05   151.533309  0.954730
Random Forest             1.279802e+05    98.840199  0.959486
Gradient Boosting         9.490228e+04   100.173359  0.969957
Support Vector Regressor  3.323279e+06  1038.424565 -0.052029

In [37]:
import pandas as pd

# Assuming results_df is already created as shown before
print(results_df)

# Find the model with the lowest MSE
best_mse_model = results_df['MSE'].idxmin()
print(f"Best model based on MSE: {best_mse_model} with MSE: {results_df['MSE'].min()}")

# Find the model with the lowest MAE
best_mae_model = results_df['MAE'].idxmin()
print(f"Best model based on MAE: {best_mae_model} with MAE: {results_df['MAE'].min()}")

# Find the model with the highest R²
best_r2_model = results_df['R²'].idxmax()
print(f"Best model based on R²: {best_r2_model} with R²: {results_df['R²'].max()}")

                                   MSE          MAE        R²
Linear Regression         5.392636e+05   430.432487  0.829289
Decision Tree             1.506061e+05   153.928015  0.952324
Random Forest             1.206557e+05    91.714340  0.961805
Gradient Boosting         9.487317e+04    99.830216  0.969967
Support Vector Regressor  3.323279e+06  1038.424565 -0.052029
Best model based on MSE: Gradient Boosting with MSE: 94873.16790861393
Best model based on MAE: Random Forest with MAE: 91.71433970588241
Best model based on R²: Gradient Boosting with R²: 0.9699666079083291

### Overall Summary: Retail Price Optimization Using Machine Learning

This project focuses on predicting retail prices to optimize pricing strategies for better profitability. Using a dataset that includes features such as quantity sold, unit price, competitor prices, and product scores, various machine learning models were developed, including Linear Regression, Decision Tree, Random Forest, Gradient Boosting, and Support Vector Regressor.

After evaluating the models based on Mean Squared Error (MSE), Mean Absolute Error (MAE), and R-squared (R²), Gradient Boosting emerged as the best model overall with the lowest MSE and highest R². This indicates its effectiveness in predicting total retail prices accurately.

The insights gained from this project can assist retailers in making data-driven pricing decisions, ultimately leading to increased sales and profitability. Future work could involve refining model parameters, integrating real-time data, and exploring additional features to enhance prediction accuracy.